name: AI PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      target_branch:
        type: string
        description: the target branch to run python from other repo
      pr_number:
        type: string
        description: the tested pr number in this repo
permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write
env:
  LLM_HOST: ${{secrets.LLM_HOST}}
  AZURE_OPENAI_ENABLED: false
  AZURE_OPENAI_URL: ${{secrets.AZURE_OPENAI_URL }}
  AZURE_OPENAI_VERSION: ${{secrets.AZURE_OPENAI_VERSION }}
  AZURE_OPENAI_KEY: ${{secrets.AZURE_OPENAI_KEY }}

jobs:
  ai-pr-review:
    runs-on: hackthon
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Checkout common-scripts repository
        uses: actions/checkout@v4
        with:
          repository: brian-ding/scaling-robot
          #ref: main
          ref: feature/castle/integrate-with-AzureOpenAI
          path: scaling-robot

      - name: Restore pip packages
        working-directory: ./scaling-robot
        run: pip install -r requirements.txt
                
      - name: PR summary
        working-directory: ./scaling-robot
        run: |
          python main.py summary -r ${{ github.event.repository.full_name }} -n ${{ github.event.pull_request.number}}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: PR code review
        working-directory: ./scaling-robot
        run: python main.py review -r ${{ github.event.repository.full_name }} -n ${{ github.event.pull_request.number}}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
