name: AI PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      target_branch:
        type: string
        description: the target branch to run python from other repo
      pr_number:
        type: string
        description: the tested pr number in this repo
permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write
env:
  LLM_HOST: ${{secrets.LLM_HOST}}

jobs:
  ai-pr-review:
    runs-on: hackthon
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Checkout common-scripts repository
        uses: actions/checkout@v4
        with:
          repository: brian-ding/scaling-robot
          ref: ${{inputs.target_branch}}
          #ref: feature/castle/add-review-and-sammary-command
          path: scaling-robot

      - name: Restore pip packages
        working-directory: ./scaling-robot
        run: pip install -r requirements.txt

      - name: PR summary
        working-directory: ./scaling-robot
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ inputs.pr_number }}
        run: |
          if [ "$PR_NUMBER" == "" ]; then
            python main.py summary -r ${{ github.event.repository.full_name }} -n ${{ github.event.pull_request.number}}
          else
            python main.py summary -r ${{ github.event.repository.full_name }} -n ${{ env.PR_NUMBER}}
          fi

      - name: PR code review
        working-directory: ./scaling-robot
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ inputs.pr_number }}
        run: |
          if [ "$PR_NUMBER" == "" ]; then
            python main.py review -r ${{ github.event.repository.full_name }} -n ${{ github.event.pull_request.number}}
          else
            python main.py review -r ${{ github.event.repository.full_name }} -n ${{ env.PR_NUMBER}}
          fi
