name: AI PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  # workflow_dispatch: {}

jobs:
  ai-pr-review:
    runs-on: hackthon
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Checkout common-scripts repository
        uses: actions/checkout@v4
        with:
          repository: brian-ding/scaling-robot
          ref: main
          path: scaling-robot

      - name: PR summary
        working-directory: ./scaling-robot
        # run: python summary -p ${{ github.event.pull_request.html_url }}
        run: ls
        
      - name: PR code review
        working-directory: ./scaling-robot
        # run: python review -p ${{ github.event.pull_request.html_url }}
        run: ls
